# version: '3'

services:
  postgres:
    image: postgres:12-alpine
    container_name: vcs-sms-db
    restart: always
    ports:
      - "$DB_PORT:5432"
    environment:
      POSTGRES_USER: vcs
      POSTGRES_PASSWORD: vcs
      POSTGRES_DB: $DB_DATABASE
    volumes:
      - vcs_sms_db_volume:/var/lib/postgresql/data

volumes:
  vcs_sms_db_volume:
