version: '3.7'

services:
  traefik:
    image: traefik:v2.3
    command:
      # traefik configuration
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.tcp.forwardedHeaders.insecure=true"
      - "--providers.docker.exposedbydefault=false"
      # tcp entrypoint
      - "--entrypoints.postgres.address=:5432"
      - "--entrypoints.redis.address=:6379"
      - "--entrypoints.kafka.address=:9092"
      - "--entrypoints.elasticsearch.address=:9200"
      # http entrypoint
      - "--entrypoints.http_mail.address=:8081"
      - "--entrypoints.http_gateway.address=:8082"
      # grpc entrypoint

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "8082:8082"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - vcs-sms-checkpoint

  gate-way:
    image: localhost:5000/gateway:latest
    env_file:
      - ./gateway/.env.container
    depends_on:
      - postgres
      - redis
      - kafka
    volumes:
      - "report-file-volume:/reports"
    networks:
      - vcs-sms-checkpoint
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.gateway.rule=Host(`localhost`)"
        - "traefik.http.services.gateway.loadbalancer.server.port=8080"

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: vcs
      POSTGRES_PASSWORD: vcs
      POSTGRES_DB: $DB_NAME
    env_file:
      - ./gateway/.env
    volumes:
      - vcs_sms_db_volume:/var/lib/postgresql/data
    networks:
      - vcs-sms-checkpoint
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.db.rule=HostSNI(`postgres.localhost`)"
      - "traefik.tcp.routers.db.entrypoints=postgres"
      - "traefik.tcp.services.db.loadbalancer.server.port=5432"

  redis:
    image: redis:alpine
    ports:
      - "$REDIS_PORT:6379"
    networks:
      - vcs-sms-checkpoint

  kafka:
    image: apache/kafka:latest
    hostname: broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://broker:9092,PLAINTEXT://broker:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    ports:
      - "9092:9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - vcs-sms-checkpoint

  health-check:
    dns:
      - 8.8.8.8
    image: localhost:5000/health-check:latest
    env_file:
      - ./health-check/.env.container
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - vcs-sms-checkpoint
    labels:
      - "traefik.enable=true"

  consumer:
    dns:
      - 8.8.8.8
    image: localhost:5000/consumer:latest
    volumes:
      - "report-file-volume:/reports"
    env_file:
      - ./consumer/.env.container
    environment:
      - ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST
      - ELASTIC_USERNAME=$ELASTIC_USERNAME
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
    depends_on:
      - kafka
    networks:
      - vcs-sms-checkpoint
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
      labels:
        - "traefik.enable=true"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_USERNAME=$ELASTIC_USERNAME
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - vcs-sms-checkpoint
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elasticsearch.rule=Host(`es.localhost`)"
      - "traefik.http.routers.elasticsearch.entrypoints=elasticsearch"
      - "traefik.http.services.elasticsearch.loadbalancer.server.port=9200"

  mail:
    image: localhost:5000/mail:latest
    volumes:
      - "report-file-volume:/reports"
    env_file:
      - ./mail/.env.container
    networks:
      - vcs-sms-checkpoint
    labels:
      - "traefik.enable=false"

volumes:
  vcs_sms_db_volume:
  report-file-volume:
    driver: local
    driver_opts:
      type: "none"
      device: "./reports"
      o: "bind"
  esdata:

networks:
  vcs-sms-checkpoint:
    driver: overlay
