definitions:
  dtos.CreateServerRequest:
    properties:
      description:
        type: string
      ip:
        type: string
      name:
        type: string
    type: object
  dtos.CreateUserRequest:
    properties:
      confirm_password:
        type: string
      email:
        type: string
      is_organization_admin:
        type: boolean
      name:
        type: string
      password:
        type: string
      phone:
        type: string
      username:
        type: string
    type: object
  dtos.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  dtos.RegisterRequest:
    properties:
      email:
        type: string
      organization_name:
        type: string
      password:
        type: string
      password_confirm:
        type: string
    required:
    - password
    - password_confirm
    type: object
  dtos.SendMailRequest:
    properties:
      from:
        description: from date
        type: string
      mail:
        type: string
      to:
        description: to date
        type: string
    type: object
  dtos.UpdateOrganizationRequest:
    properties:
      address:
        type: string
      alias_name:
        type: string
      description:
        type: string
      establishment_date:
        type: string
      name:
        type: string
      website_url:
        type: string
    type: object
  dtos.UpdateServerRequest:
    properties:
      description:
        type: string
      ip:
        type: string
      name:
        type: string
    type: object
  dtos.UpdateUserRequest:
    properties:
      confirm_password:
        type: string
      email:
        type: string
      is_organization_admin:
        type: boolean
      name:
        type: string
      password:
        type: string
      phone:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  description: This is a sample server VCS SMS API server.
  title: VCS SMS API
  version: "1"
paths:
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: Login Request
        in: body
        name: loginReq
        required: true
        schema:
          $ref: '#/definitions/dtos.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Login
      tags:
      - Authentication
  /api/v1/auth/logout:
    post:
      consumes:
      - application/json
      description: Logout
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Logout
      tags:
      - Authentication
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      description: Register
      parameters:
      - description: Register Request
        in: body
        name: registerReq
        required: true
        schema:
          $ref: '#/definitions/dtos.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Register
      tags:
      - Authentication
  /api/v1/auth/validate:
    get:
      consumes:
      - application/json
      description: Validate
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Validate
      tags:
      - Authentication
  /api/v1/organizations/:
    get:
      consumes:
      - application/json
      description: Get organization
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get organization
      tags:
      - Organization
  /api/v1/organizations/{orgID}:
    put:
      consumes:
      - application/json
      description: Update organization
      parameters:
      - description: Update Organization Request
        in: body
        name: UpdateOrganizationBodyRequest
        required: true
        schema:
          $ref: '#/definitions/dtos.UpdateOrganizationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Update organization
      tags:
      - Organization
  /api/v1/ping:
    get:
      consumes:
      - application/json
      description: Ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Ping
      tags:
      - Ping
  /api/v1/servers:
    get:
      consumes:
      - application/json
      description: Get all servers
      parameters:
      - description: Page
        in: query
        name: page
        type: integer
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Search
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get all servers
      tags:
      - Server
    post:
      consumes:
      - application/json
      description: Create a new server
      parameters:
      - description: Create Server Request
        in: body
        name: CreateServerBodyRequest
        required: true
        schema:
          $ref: '#/definitions/dtos.CreateServerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Create a new server
      tags:
      - Server
  /api/v1/servers/{id}:
    delete:
      consumes:
      - application/json
      description: Delete server
      parameters:
      - description: Server ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Delete server
      tags:
      - Server
    get:
      consumes:
      - application/json
      description: Get server by ID
      parameters:
      - description: Server ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get server by ID
      tags:
      - Server
    put:
      consumes:
      - application/json
      description: Update server
      parameters:
      - description: Server ID
        in: path
        name: id
        required: true
        type: string
      - description: Update Server Request
        in: body
        name: UpdateServerBodyRequest
        required: true
        schema:
          $ref: '#/definitions/dtos.UpdateServerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Update server
      tags:
      - Server
  /api/v1/servers/{id}/archive:
    patch:
      consumes:
      - application/json
      description: Archive server
      parameters:
      - description: Server ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Archive server
      tags:
      - Server
  /api/v1/servers/{id}/restore:
    patch:
      consumes:
      - application/json
      description: Archive server
      parameters:
      - description: Server ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Archive server
      tags:
      - Server
  /api/v1/servers/archived:
    get:
      consumes:
      - application/json
      description: Archive server
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: GetArchivedServer server
      tags:
      - Server
  /api/v1/servers/download-template:
    get:
      consumes:
      - application/json
      description: Send to client file template from ./files/server_list_template.xlsx
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Download template
      tags:
      - Server
  /api/v1/servers/send-report:
    post:
      consumes:
      - application/json
      description: Send report by mail
      parameters:
      - description: Send Report by Mail Request Date is YYYY-MM-DD
        in: body
        name: SendMailRequest
        required: true
        schema:
          $ref: '#/definitions/dtos.SendMailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Send report by mail
      tags:
      - Server
  /api/v1/servers/upload:
    post:
      consumes:
      - application/json
      description: Upload server list from client .xlsx file
      parameters:
      - description: Server list file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Upload server list
      tags:
      - Server
  /api/v1/users:
    get:
      consumes:
      - application/json
      description: Get all users
      parameters:
      - description: Page
        in: query
        name: page
        type: integer
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Search
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Get all users
      tags:
      - User
    post:
      consumes:
      - application/json
      description: Create user
      parameters:
      - description: Create User Request
        in: body
        name: createReq
        required: true
        schema:
          $ref: '#/definitions/dtos.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Create user
      tags:
      - User
  /api/v1/users/{user_id}:
    get:
      consumes:
      - application/json
      description: Get user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get user by ID
      tags:
      - User
    put:
      consumes:
      - application/json
      description: Update user
      parameters:
      - description: Update User Request
        in: body
        name: updateReq
        required: true
        schema:
          $ref: '#/definitions/dtos.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Update user
      tags:
      - User
  /api/v1/users/{user_id}/archive:
    patch:
      consumes:
      - application/json
      description: Delete user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Delete user
      tags:
      - User
  /api/v1/users/{user_id}/unarchive:
    patch:
      consumes:
      - application/json
      description: Delete user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Delete user
      tags:
      - User
  /api/v1/users/archived:
    get:
      consumes:
      - application/json
      description: Get all archived users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get all archived users
      tags:
      - User
security:
- ApiKeyAuth: []
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
